[package]
name = "cargo_and_crates_fairyhunter13"
version = "0.1.1"
authors = ["fairyhunter13 <fairyhunter13@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Learning the features of cargo and crates in rust."

[dependencies]

[profile.dev]
opt-level=1
